### ISSUE TITLE
Сделать альтернативную форму для Заказать расчет

### ISSUE THREAD

**Issue by Sashamailrias** [nicolaypetrovich/rocket-avrial#16]
Макет формы https://drive.google.com/file/d/1DnPnaUoUWSBDKjOAHVbrYoZABNKFTkIF/view?usp=sharing

**Comment by VladyslavKovalchuk** [comment]
http://prntscr.com/kx09p0

**Comment by Sashamailrias** [comment]
Нужно вместо поля срочность завершения написать "цель запроса КП" и варианты в виде Выпадающего списка: 
1. Бизнес-идея/бизнес-план 
2. Составление бюджета на ближайший год 
3. Выбор подрядчика

**Comment by VladyslavKovalchuk** [comment]
http://prntscr.com/kyk8fx увеличить отступ слева для капчи, как у блоков выше

**Comment by VladyslavKovalchuk** [comment]
на телефоне сместить форму ниже, сильно уползает вверх
http://prntscr.com/kyzuma
