### ISSUE TITLE
Тестировщику - На стр. О компании, текст вылазит за блоки

### ISSUE THREAD

**Issue by Sashamailrias** [nicolaypetrovich/rocket-avrial#17]
1. Нужно заполнить контент стр. о компании, то есть добавить длинные заголовки и большое описание http://avrial.rocketcompany.website/kompaniya
2. Нужно протестить выбор блоков http://prntscr.com/kwkm6t  http://prntscr.com/kwkmib  http://prntscr.com/kwkmn9
По итогу у заказчика должна быть возможность выбрать нужный блок для нужного раздела.

**Comment by VladyslavKovalchuk** [comment]
после добавления текста в блоки "Компания сегодня" (блок с изобр. справа и блок с изобр. слева) ломаются все блоки после блока компания вчера
