### ISSUE TITLE
Переставить метки на карте 

### ISSUE THREAD

**Issue by Sashamailrias** [nicolaypetrovich/rocket-avrial#20]
Как должно быть https://drive.google.com/open?id=15PadRbRPkanG6mQSqeFUEdVDJMODT9Ey

**Comment by VladyslavKovalchuk** [comment]
http://prntscr.com/kx0auf
не совсем как там

**Comment by Sashamailrias** [comment]
Переставить 2 метки на карте как на скрине  http://prntscr.com/ky1u4q
