### ISSUE TITLE
Сделать заголовки h1

### ISSUE THREAD

**Issue by Sashamailrias** [nicolaypetrovich/rocket-avrial#27]
1. На страницах полного ответа на вопросы ( пример такой стр. http://avrial.rocketcompany.website/voprosy/podryad)
2. Статьях и новостях (пример http://prntscr.com/kx1wpu http://avrial.rocketcompany.website/blog-kompanii/peregorodki-iz-sendvich-panelej-osobennosti-i-preimushhestva-ispolzovaniya)

**Comment by Mugenzo** [comment]
что тут не так?
