### ISSUE TITLE
Пропал отступ

### ISSUE THREAD

**Issue by Sashamailrias** [nicolaypetrovich/rocket-avrial#28]
После выполнения задачи с обрезание заголовков http://prntscr.com/ktwhbj
http://prntscr.com/ktwhnd , пропал отступ
Как сейчас  http://prntscr.com/kx1yu2 
Как должно быть http://prntscr.com/kx1yir ( http://evrial.citytyumen.ru/uslugi )

**Comment by VladyslavKovalchuk** [comment]
http://prntscr.com/kxyz01
