### ISSUE TITLE
ломается блок "нас благодарят" - о компании, пк и моб версия

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [nicolaypetrovich/rocket-avrial#30]
http://prntscr.com/kxzalj
http://prntscr.com/kxzbdp
http://prntscr.com/kxzbq5

**Comment by Sashamailrias** [comment]
https://prnt.sc/kyk9f8

**Comment by VladyslavKovalchuk** [comment]
убрать прозрачную рамку при ширине меньше 1200рх
