### ISSUE TITLE
при ресайзе (992-1008рх) ломается хедер

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [nicolaypetrovich/rocket-avrial#35]
http://prntscr.com/ky01x8 - фф
в опере при 992рх исчезает кнопка "обратный звонок"
http://prntscr.com/ky02j9 - хром
http://prntscr.com/ky03y4 - ие11
http://prntscr.com/ky046d - едж

**Comment by VladyslavKovalchuk** [comment]
974-991 - фф http://prntscr.com/l3keex
опера то же
хром 990-991
то же едж
ие11 - 991рх, http://prntscr.com/l3khu3

**Comment by SeregaWeb** [comment]
Саша сказала подходит
