### ISSUE TITLE
Сделать блоки по макету

### ISSUE THREAD

**Issue by Sashamailrias** [nicolaypetrovich/rocket-avrial#36]
Нужно попровнять иконки и текст в 1 и 2 блоке http://prntscr.com/ky1qd1 как на макете 
https://drive.google.com/file/d/16Ya7S1cGpLgAodf7qlOIpQBYiSqKAwr4/view?usp=sharing

**Comment by VladyslavKovalchuk** [comment]
пересмотреть ширину текста, в макете отличается http://prntscr.com/l3kjte
