### ISSUE TITLE
Иконки в услугах в некоторых зонах обрезаются 

### ISSUE THREAD

**Issue by Sashamailrias** [nicolaypetrovich/rocket-avrial#61]
Иконки в услугах в некоторых зонах обрезаются 
Пример http://prntscr.com/kzdjcx
http://avrial.rocketcompany.website/uslugi/gibridnye-zdaniya

**Comment by VladyslavKovalchuk** [comment]
не грузит иконки http://prntscr.com/l3k6xu

**Comment by SeregaWeb** [comment]
На нашем тестовом сайте половины картинок нет , там все сделано
