### ISSUE TITLE
Добавить почту разделу работники 

### ISSUE THREAD

**Issue by Sashamailrias** [nicolaypetrovich/rocket-avrial#69]
Добавить почту разделу работники http://prntscr.com/l16dbc 
Сделать в админке поле для редактирования почты

**Comment by VladyslavKovalchuk** [comment]
http://prntscr.com/l3yhc0 - не помещается и фона налазит сверху

**Comment by Mugenzo** [comment]
20 минут

**Comment by SeregaWeb** [comment]
20 минут
