### ISSUE TITLE
Добавить увеличение картинок О компании

### ISSUE THREAD

**Issue by Sashamailrias** [nicolaypetrovich/rocket-avrial#73]
Добавить увеличение картинок в разделы Вчера, Сегодне, Завтра.

**Comment by VladyslavKovalchuk** [comment]
увеличение есть только в "компания завтра"

**Comment by SeregaWeb** [comment]
http://prntscr.com/l3wjla размер картинок отдается через WP я вывод добавил

**Comment by SeregaWeb** [comment]
30 минут
