### ISSUE TITLE
Увеличить размер меню, что б влез текст "СТРОИТЕЛЬНЫЙ БЛОГ"

### ISSUE THREAD

**Issue by Sashamailrias** [nicolaypetrovich/rocket-avrial#9]
http://avrial.rocketcompany.website/
Вместо вкладки информационная https://prnt.sc/ktw8pv  должно быть название "Строительный блог". Пр  меньших разрешениях, оно не должно перестраиваться на следующую строку, а влезть в 1.

**Comment by VladyslavKovalchuk** [comment]
http://prntscr.com/kwzbep в ие11 и в едже
